version: "3"

services:
  agendav:
    build:
      context: ./agendav-docker
      dockerfile: Dockerfile
    container_name: caldav_frontend
    volumes:
      # Required: your AgenDAV configuration
      - ./agendav-config/settings.php:/var/www/agendav/web/config/settings.php:ro
      - agendav_data:/var/agendav
    ports:
      - '127.0.0.1:9002:8080'

volumes:
  agendav_data:
  
#~ networks:
  #~ default:
    #~ ipam:
      #~ config:
        #~ - subnet: 192.168.96.0/24
          #~ gateway: 192.168.96.1
