[www]
; Override the listen address to a Unix socket.
; Any directives here take precedence over the defaults in www.conf.
listen = /run/php-fpm.sock
listen.owner = root
listen.group = root
listen.mode = 0666
